version: "3.9"
services:
  reclamacaodb:
    image: mysql:latest
    container_name: reclamacaodb
    restart: unless-stopped
    env_file: ./.env    
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE    
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/reclamacaodb
 
  app_reclamacao:
    image: backend/app_reclamacao:1.0
    container_name: app_reclamacao    
    restart: on-failure
    depends_on:
      - reclamacaodb
    env_file: ./.env
    build: ./incidisfy-backend-reclamacao      
    ports:      
      - $APP_RECLAMACAO_LOCAL_PORT:$APP_RECLAMACAO_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://reclamacaodb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?allowPublicKeyRetrieval=true&useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
        }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: